"""DEFAULT_CONFIG_YAML_TEMPLATE (autogenerated at runtime, no repo access) and
photoarchive_config.yaml.example (read by anyone browsing the source) duplicate the same
text on purpose (see photosort_win.py comment above DEFAULT_CONFIG_YAML_TEMPLATE) -- nothing
enforced them staying in sync before this test (REVIEW-HANDOFF.md round 13, ticket 2b;
originally flagged 2026-07-11). Guards against silent drift: an edit to one without the other
now fails CI on any push, not just "eventually noticed"."""
import os

import photosort_win as m

# Intro block is intentionally different: the template addresses users with no repo access
# (autocreated file), the .example addresses people editing the repo directly.
_TEMPLATE_INTRO_LINES = slice(9, 13)
_EXAMPLE_INTRO_LINES = slice(9, 14)


def test_template_and_example_match_outside_intro_block():
    template_lines = m.DEFAULT_CONFIG_YAML_TEMPLATE.splitlines()
    example_path = os.path.join(os.path.dirname(m.__file__), "photoarchive_config.yaml.example")
    with open(example_path, encoding="utf-8") as f:
        example_lines = f.read().splitlines()

    assert template_lines[:9] == example_lines[:9]
    assert template_lines[_TEMPLATE_INTRO_LINES.stop:] == example_lines[_EXAMPLE_INTRO_LINES.stop:]
